version: '3'
services:
  web:
    build: .
    ports:
      - "3000:8080"
    environment:
      DB_HOST: db
  db:
    image: postgres
    ports:
     - "6543:5432"
    environment:
      POSTGRES_PASSWORD: yourpaswd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
